name: Deploy a cPanel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Deploy via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: mx126.hostgator.mx
          username: twistedp
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./"
          target: "/home3/twistedp/public_html"
          rm: false
